[workspace]
name = "filer"
resolver = "3"
members = ["filer-app", "filer-core"]

[workspace.dependencies]
tokio = {version = "1", features = ["full"]}
tracing = "0.1.44"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"